var siteBaseUrl = "https://docs.vantainteractive.com/";

//function langDropdownBtn() {var dropdownMenu = document.getElementById('languageDropdownMenu');dropdownMenu.classList.toggle('flex');};
//document.addEventListener('click', function(event) {var dropdownButton = document.getElementById('languageDropdownButton');var dropdownMenu = document.getElementById('languageDropdownMenu');if (!dropdownButton.contains(event.target)) {dropdownMenu.classList.remove('show');}});
//document.querySelectorAll('#languageDropdownMenu .dropdown-item').forEach(item => {item.addEventListener('click', event => {event.preventDefault();var lang = event.target.getAttribute('data-lang');var currentUrl = window.location.href;var newUrl = currentUrl.replace(/\/[a-z]{2}\//, '/' + lang + '/');var selectedProject = document.querySelector('.sidebar-dropdown-item.selected');if (selectedProject) {var project = selectedProject.getAttribute('data-project');newUrl += project + '/';}window.location.href = newUrl;});});

function sidebarProjectDropdownBtn() {var projectDropdownMenu = document.getElementById('projectDropdownMenu');projectDropdownMenu.classList.toggle('flex');};document.addEventListener('click', function(event) {var projectDropdownButton = document.getElementById('projectDropdownButton');var projectDropdownMenu = document.getElementById('projectDropdownMenu');if (!projectDropdownButton.contains(event.target)) {projectDropdownMenu.classList.remove('show');}});
document.querySelectorAll('#projectDropdownMenu .sidebar-dropdown-item').forEach(item => {item.addEventListener('click', event => {event.preventDefault();var project = event.target.getAttribute('data-project');var currentUrl = window.location.href;var langRegex = /\/[a-z]{2}\//;var langMatch = currentUrl.match(langRegex);var lang = langMatch ? langMatch[0].replace(/\//g, '') : '';var baseUrl = currentUrl.replace(langRegex, '/' + lang + '/');var newUrl = siteBaseUrl + (lang ? lang + '/' : '') + project + '/';window.location.href = newUrl;});});
function adjustContentWidth() {var sidebar = document.getElementById('sidebar');var docColumnRight = document.querySelector('.doc-column-right');if (sidebar.classList.contains('sidebar-collapsed')) {docColumnRight.style.paddingLeft = '0';} else {var sidebarWidth = sidebar.offsetWidth;docColumnRight.style.paddingLeft = sidebarWidth + 'px';}}

function sidebarCollapseButton() {var sidebar = document.getElementById('sidebar');var sidebarBrand = document.getElementById('sidebar-branding');var sidebarBrandlogo = document.getElementById('branding-logo');var sidebarBrandname = document.getElementById('branding-name');var sidebarContent = document.getElementById('sidebar-content');var sidebarCollapseButton = document.getElementById('sidebarCollapseButton');sidebar.classList.toggle('sidebar-collapsed');sidebarContent.classList.toggle('hidden');sidebarBrand.classList.toggle('flex');sidebarBrandlogo.classList.toggle('hidden');sidebarBrandname.classList.toggle('hidden');setTimeout(function() {adjustContentWidth();}, 300);};window.onload = function() {adjustContentWidth();};window.onresize = function() {adjustContentWidth();};
